src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\FormTypeInterface;

/**
 * @ORM\Entity(repositoryClass=ArticlesRepository::class)
 */
class Articles
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Redacteur;

    /**
     * @ORM\Column(type="text")
     */
    private $Contenu;

    /**
     * @ORM\ManyToOne(targetEntity=Type::class, inversedBy="articles")
     */
    private $Type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getRedacteur(): ?string
    {
        return $this->Redacteur;
    }

    public function setRedacteur(string $Redacteur): self
    {
        $this->Redacteur = $Redacteur;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->Type;
    }

    public function setType(?Type $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
    /**
     * Transform to string
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getNom();

    }
}

src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\Articles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormTypeInterface;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Type')
            ->add('Image')
            ->add('Redacteur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormTypeInterface;

class ArticlesController extends AbstractController
{

    /**
     * @Route("/articles", name="app_articles_index", methods="GET")
     */
    public function index(ArticlesRepository $articlesRepository)
    {
        $articles = $articlesRepository ->findAll();
        return $this->render('articles\index.html.twig',['articles'=>$articles]);
    }
    /**
     * @Route("/articles/{titre}", name="article")
     */
    public function aaa(ArticlesRepository $repository, $titre)
    {
        $articlesPage = $repository->findBy(['titre' => $titre]);
        return $this->render('articles/index.html.twig', [
            'articles' => $articlesPage
        ]);
    }


    /**
     * @Route("articles/create", name="app_articles_create", methods={"GET","POST"})
     */
    public function create(Request $request, EntityManagerInterface $manager)
    {
        $articles = new Articles();
        // Créer le formulatire
        $form = $this->createForm(Articles::class, $articles);
        // Créer la soumission du formulaire
        // Analyser la requete HTTP
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($articles);
            $manager->flush();
            // Flash message
            $this->addFlash('success', 'Article ajouté avec succes');
            return $this->redirectToRoute('app_articles_index');
        }
        // Appel à la vue pour afficher le formulaire
        return $this->render('articles/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

}

templates/articles/_form.html.twig
{# Partial #}

{{ form_start(form) }} <!-- Creer la balise form -->
{{ form_row(form.nom,
    {'attr' : {
        'placeholder' : "Nom de l'article"},
        'label' : "Titre article"}
) }}

    {{ form_row(form.type,
        {'attr' : {
            'placeholder' : "Type Article"},
            'label' : "Type"}
    ) }}

    {{ form_row(form.redacteur,
        {'attr' : {
            'placeholder' : "Nom du redacteur"},
            'label' : "Redacteur"}
    ) }}

    {{ form_row(form.proteine,
        {'attr' : {
            'placeholder' : "Img"},
            'label' : "Images"}
    ) }}


<input type="submit" value="{{ submitButtonText }}" class="btn btn-success">

{{ form_end(form) }} <!-- Fermer la balise form -->

templates/articles/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin aliments{% endblock %}
{% block titrePage %}Création d'un aliment{% endblock %}

{% block body %}

    {{ include ('articles/_form.html.twig', {'submitButtonText' : 'Créer'}) }}

{% endblock %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticlesController!{% endblock %}

{% block body %}
        {% for article in articles %}
            <tr class="text-center">
                <td>{{ article.Nom }}</td>
                <td>{{ article.Redacteur }}</td>
                <td>{{ article.Contenu }}</td>
                <img src="{{ article.Image }}"/>
                <td>
                    <a href="" class="btn btn-secondary mb-2">Modifier</a>
                    <a href="" class="btn btn-dark mb-2">Supprimer</a>
                </td>
            </tr>
        {% endfor %}
{% endblock %}